Repository TECH7Fox/asterisk-hass-addons, pull requests merged in 2022-02, with the labels that each got.

#75 Move translations to docs
  asterisk/DOCS.md
  asterisk/translations/en.yaml
Labels: documentation

#68 Add asterisk_mbox service
  asterisk/DOCS.md
  asterisk/Dockerfile
  asterisk/build.yaml
  asterisk/config.yaml
  asterisk/rootfs/etc/cont-init.d/asterisk.sh
  asterisk/rootfs/etc/services.d/asterisk_mbox/finish
  asterisk/rootfs/etc/services.d/asterisk_mbox/run
  asterisk/rootfs/usr/share/tempio/asterisk_mbox.ini.gtpl
  asterisk/translations/en.yaml
Labels: enhancement

#79 1.1.1
  asterisk/DOCS.md
  asterisk/config.yaml
  asterisk/translations/en.yaml
Labels: documentation

#85 Fix permission denied error in discovery service
  .devcontainer/devcontainer.json
  asterisk/CHANGELOG.md
  asterisk/config.yaml
  asterisk/rootfs/etc/services.d/asterisk/run
  asterisk/rootfs/etc/services.d/asterisk_mbox/run
  asterisk/rootfs/etc/services.d/discovery/run
Labels: bug
